<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Kezzo-LT" failures="1" tests="1" name="Happy Scenarios 1" time="7.647" errors="0" timestamp="2020-11-14T02:36:25 EET">
  <testcase classname="tests.ContactUsTest" name="UserCanUseContactUs" time="7.241">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.ContactUsTest.UserCanUseContactUs(ContactUsTest.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- UserCanUseContactUs -->
</testsuite> <!-- Happy Scenarios 1 -->
